### ISSUE TITLE
Doesn't work in safari

### ISSUE THREAD

**Issue by foca** [elcuervo/whereisfoca.com#2]
Low priority, as I'm probably the only person in the _WORLD_ that uses safari, but the map shows Montevideo and then instead of moving to where I am, it goes plain grey.

**Comment by elcuervo** [comment]
Oh my Lord. Forgive this peasant the fix was committed and my newborn sacrificed to the new gods. Please have mercy of my soul.

![](http://marketpunch.com/wp-content/uploads/2014/09/notworthy.gif)
